name: clang-tidy stdlib issue

on:
  push:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpp: [clang++-14, g++-11]
    steps:
      - uses: actions/checkout@v2

      # In production we compile with GCC 11. libstdc++ contains <source_location>, libc++ does not.
      - run: |
          sudo apt install g++-11
          sudo apt update

      - run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14 all

      - run: clang-tidy-14 --version

      - run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER=${{ matrix.cpp }}

      - run: cmake -B build

      - uses: actions/upload-artifact@v2
        with:
          name: compile_commands.json
          path: build/compile_commands.json

      # Error: namespace std not found
      # This means clang-tidy is picking libstdc++ where <source_location> exists regardless of
      # which compiler we use to build the project.
      # libstdc++ conditionally defines std::source_location only if __builtin_source_location exists
      # which it does not when building with clang/clang-tidy.
      - run: |
          clang-tidy-14 -p build --dump-config
          clang-tidy-14 -p build ./main.cpp
